# Generated by Django 5.2.7 on 2026-02-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evreyting', '0008_delete_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب')),
                ('html_content', models.TextField(verbose_name='كود HTML للقالب')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, verbose_name='الصف الدراسي')),
                ('semester', models.CharField(max_length=100, verbose_name='الترم')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('prompt', models.TextField(verbose_name='وصف الطلب')),
                ('questions_json', models.JSONField(blank=True, null=True, verbose_name='الأسئلة (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
